version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app
    restart: always
    working_dir: /var/www/
    volumes:
      - ../../MVC_Framework_from_Scratch_php:/var/www
  nginx:
    image: nginx:1.19-alpine
    container_name: nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ../../Wiederholungsprojekt:/var/www
      - ./nginx:/etc/nginx/conf.d
  db:
    image: mysql:5.7
    #gibt zoff
    container_name: db
    #gibt zoff
    environment:
      MYSQL_ROOT_PASSWORD: aA1234Aa
      MYSQL_DATABASE: mvc-db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass
    ports:
      - "6033:3306"
    volumes:
      - ../runtime/dbdata:/var/lib/mysql
volumes:
  dbdata:


  #docker exec -it personalwebsite-db  mysql -uroot -p
  # /var/run/mysqld/mysqld.sock
  #/usr/local/etc/php